#/
# @license Apache-2.0
#
# Copyright (c) 2017 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

version: "2"

# Configure maintainability [checks][1].
#
# [1]: https://docs.codeclimate.com/docs/advanced-configuration
checks:
  # Check for methods or functions defined with a high number of arguments.
  argument-count:
    enabled: true
    config:
      threshold: 4

  # Check for boolean logic that may be hard to understand.
  complex-logic:
    enabled: true
    config:
      threshold: 4

  # Check for excessive lines of code within a single file.
  file-lines:
    enabled: true
    config:
      threshold: 300

  # Check for functions or methods that may be hard to understand (cognitive complexity).
  method-complexity:
    enabled: true
    config:
      threshold: 5

  # Check for classes defined with a high number of functions or methods.
  method-count:
    enabled: true
    config:
      threshold: 20

  # Check for excessive lines of code within a single function or method.
  method-lines:
    enabled: true
    config:
      threshold: 100

  # Check for deeply nested control structures like `if` or `case`.
  nested-control-flow:
    enabled: true
    config:
      threshold: 4

  # Check for functions or methods with a high number of return statements.
  return-statements:
    enabled: true
    config:
      threshold: 5

  # Check for duplicate code which is not identical but shares the same structure (e.g., variable names may differ).
  similar-code:
    enabled: true

  # Check for duplicate code which is syntactically identical (but may be formatted differently).
  identical-code:
    enabled: true

# Enable analysis [plugins][1].
#
# [1]: https://docs.codeclimate.com/docs/list-of-engines
plugins:
  # Analyze C/C++ files using [Cppcheck][1].
  #
  # [1]: https://docs.codeclimate.com/docs/cppcheck
  cppcheck:
    enabled: true
    config:
      check: all

  # Analyze CSS files using [CSSLint][1].
  #
  # [1]: https://docs.codeclimate.com/docs/csslint
  csslint:
    enabled: true

  # Analyze files using [EditorConfig][1].
  #
  # [1]: https://docs.codeclimate.com/docs/editorconfig
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig

  # Analyze JavaScript files using [ESLint][1].
  #
  # [1]:https://docs.codeclimate.com/docs/eslint
  eslint:
    enabled: false  # NOTE: disabled as CodeClimate does not support external configurations or network calls (see https://github.com/codeclimate/codeclimate-eslint/issues/86), and we rely on ESLint plugins which require network access, something CodeClimate does not permit
    channel: "eslint-6"
    config:
      config: .eslintrc.js
      extensions:
        - .js

  # Analyze source files for annotations using [fixme][1].
  #
  # [1]: https://docs.codeclimate.com/docs/fixme
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - WARNING
        - HACK
        - NOTE
        - OPTIMIZE
        - BUG
        - XXX

  # Analyze the complexity of C functions using [GNU Complexity][1].
  #
  # [1]: https://docs.codeclimate.com/docs/gnu-complexity
  gnu-complexity:
    enabled: true

  # Analyze Markdown files using [markdownlint][1].
  #
  # [1]: https://github.com/mivok/markdownlint
  markdownlint:
    enabled: false

  # Audit Node.js dependencies for security vulnerabilities using [Node Security][1].
  #
  # [1]: https://github.com/nodesecurity/nsp
  nodesecurity:
    enabled: true

  # Analyze Python files using [Pep8][1].
  #
  # [1]: https://www.python.org/dev/peps/pep-0008/
  pep8:
    enabled: true

  # Lint Python files using [Pylint][1].
  #
  # [1]: https://docs.codeclimate.com/docs/pylint
  pylint:
    enabled: true

  # Analyze bash files using [shellcheck][1].
  #
  # [1]: https://github.com/koalaman/shellcheck
  shellcheck:
    enabled: true

# Specify which files/folders should be [ignored][1] when performing analyses.
#
# [1]: https://docs.codeclimate.com/docs/excluding-files-and-folders
exclude_patterns:
  - "node_modules/"
  - "reports/"
  - "build/"
  - "deps/"
  - "dist/"
  - "docs/"
  - "etc/"
  - "test/"
  - "tmp/"
  - "workshops/"
  - "**/benchmark/"
  - "**/build/"
  - "**/docs/"
  - "**/etc/"
  - "**/examples/"
  - "**/scripts/"
  - "**/test/"
  - "**/tmp/"
