# After changing this file, check it on:
#   http://lint.travis-ci.org/
#
# Known lint bugs:
#   - addons: https://github.com/travis-ci/travis-yaml/issues/58
#   - osx: https://github.com/travis-ci/travis-yaml/issues/95

language: node_js

# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: true

os:
  - linux
  - osx

node_js:
  # Node.js
  - 'node'
  - '6'
  - '5'
  - '4'
  # io.js
  - '3'
  - '2'
  - '1'
  # Node.js
  - '0.12'
  - '0.10'

env:
  # Environment variables common to all jobs:
  global:
    - CXX=g++-4.8

  # Environment variables used to construct build matrix:
  matrix:
    - BUILD_TASK='test'
    - BUILD_TASK='benchmark'
    - BUILD_TASK='examples'
    - BUILD_TASK='test-coverage'


matrix:
  # Flag to immediately finish a build if any one of the jobs fails:
  fast_finish: true


# Compiling native modules for io.js v3.x.x or Node.js >=v4.0.0 requires a C++11 standard-compliant compiler. Specifically, either gcc >=4.8 or clang >=3.5.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


# Set the clone depth:
git:
  depth: 10


before_install:
  # Update the npm client. Older clients cannot, e.g., handle scoped modules.
  - npm update -g npm


script:
  - chmod +x ./tools/ci/travis
  - "./tools/ci/travis $BUILD_TASK"

