# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: node_js

# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: true

os:
  - linux
  - osx

node_js:
  # Node.js
  - 'node'
  - '6'
  - '5'
  - '4'
  # io.js
  - '3'
  - '2'
  - '1'
  # Node.js
  - '0.12'
  - '0.10'

before_install:
  # Update the npm client. Older clients cannot, e.g., handle scoped modules.
  - npm update -g npm

script:
  - ./tools/ci/travis.sh

