# After changing this file, check it on:
#   http://lint.travis-ci.org/
#
# Known lint bugs:
#   - addons: https://github.com/travis-ci/travis-yaml/issues/58
#   - osx: https://github.com/travis-ci/travis-yaml/issues/95

language: node_js

# Is `sudo` required? If not, jobs are run on container-based infrastructure.
sudo: true

os:
  - linux
  - osx

node_js:
  # Node.js
  - 'node'
  - '6'
  - '5'
  - '4'
  # io.js
  - '3'
  - '2'
  - '1'
  # Node.js
  - '0.12'
  - '0.10'

env:
  # Environment variables common to all jobs:
  global:
    - CXX=g++-4.8

  # Environment variables used to construct build matrix:
  matrix:
    - BUILD_TASK='test'
    - BUILD_TASK='benchmark'
    - BUILD_TASK='examples'
    - BUILD_TASK='test-coverage'


matrix:
  # Flag to immediately finish a build if any one of the jobs fails:
  fast_finish: true


# Compiling native modules for io.js v3.x.x or Node.js >=v4.0.0 requires a C++11 standard-compliant compiler. Specifically, either gcc >=4.8 or clang >=3.5.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


# Set the clone depth:
git:
  depth: 50


before_install:
  # Update the npm client. Older clients cannot, e.g., handle scoped modules.
  - npm update -g npm


script:
  - chmod +x ./tools/ci/travis
  - "./tools/ci/travis $BUILD_TASK"


notifications:
  slack:
    rooms:
      secure: "3r3vY1UbfIMqoWX46XxCxmczqYE9eMe6I4PrYO9V9a03vFfLaZ/GzzdlqrdtL43jRC45xQP4tjnmj6kg4xtn6nUpZ5SzBnMknR41vzOK0wLxAmCBLNKnOWzyrhk7IDuGM9KpwGADxcNaVHY909MZsPTZd+BNm/eJJPINdTEio5F7quLfQSPfWUOW+LTsNeS+tI3pprzy2XiupyTz0OCC1CIXgTzJXvI0I5x6P+GHeTInkmHmLUJV3VCQsEPfmz93x5oCcsnkLyw79TBJlEC+2VyAbubJt+AuYyf/bV55k5GRJnJugaeTAUCBjlKbl1b/IA8dW6cr40ORPe+75bW4oLCsl34284Bwxf/dbyRY13GMqPkWgzW+PXAvwaXHS2z/q9NvOpLbX+LD+N0HHSAZB0WppJqI7ZKo06xLpVHi8RiK615HqALaMX/ujMR8ZZtTQKKSY683YDOYrG2JpjJX70VUMwdKN1ZzDkV9VbxCWAtotPR5u1n+PvQ8ihfLVDX3q5kRkDKvpGMJjZ1EFlbiUBN4hwZ9r9sQnQ5SI9ZIC81JEpfFwkCvdzrbGE6z4XfzfHPw9YMoYaDYQxq4tbyjtLYqrXCOEfBZ+egx0r9/5rrx+k5RnsfMgUXoSog5HfMknoiDFcQKFeGoxWj0NlyAEA44ozH/KMbz2DKSvvjtvS4="
