#/
# @license Apache-2.0
#
# Copyright (c) 2022 The Stdlib Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#/

# Workflow name:
name: run_affected_tests

# Workflow triggers:
on:
  push:
    paths:
      # List paths for which changes should trigger this workflow:
      - 'lib/**/bin/**'
      - 'lib/**/data/**'
      - 'lib/**/etc/**'
      - 'lib/**/include/**'
      - 'lib/**/lib/**'
      - 'lib/**/src/**'
      - 'lib/**/test/**'

      - 'lib/**/*.gyp'
      - 'lib/**/*.gypi'
      - 'lib/**/manifest.json'

      - 'package.json'

      # List paths for which changes should *not* trigger this workflow:
      - '!lib/**/_tools/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      # List paths for which changes should trigger this workflow:
      - 'lib/**/bin/**'
      - 'lib/**/data/**'
      - 'lib/**/etc/**'
      - 'lib/**/include/**'
      - 'lib/**/lib/**'
      - 'lib/**/src/**'
      - 'lib/**/test/**'

      - 'lib/**/*.gyp'
      - 'lib/**/*.gypi'
      - 'lib/**/manifest.json'

      - 'package.json'

      # List paths for which changes should *not* trigger this workflow:
      - '!lib/**/_tools/**'

  workflow_dispatch:
    inputs:
      files:
        description: 'List of changed files for which to run affected tests (space separated):'

# Workflow jobs:
jobs:

  # Define a job for running tests affected by changes to the repository...
  process:

    # Define a display name:
    name: 'Run affected tests'

    # Define the type of virtual host machine:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          # Specify whether to remove untracked files before checking out the repository:
          clean: true

          # Limit clone depth to the last 1000 commits:
          fetch-depth: 1000

          # Specify whether to download Git-LFS files:
          lfs: false
        timeout-minutes: 10

      # Install Node.js:
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 'lts/*'
        timeout-minutes: 5

      # Install dependencies (accounting for possible network failures, etc, when installing node module dependencies):
      - name: 'Install dependencies'
        run: |
          make install-node-modules || make install-node-modules || make install-node-modules
        timeout-minutes: 15

      # Initialize development environment:
      - name: 'Initialize development environment'
        run: |
          make init
        timeout-minutes: 5

      # Get list of changed files from PR and push events:
      - name: 'Get list of changed files'
        if: github.event_name != 'workflow_dispatch'
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          separator: ' '
          dir_names: 'true'

      # Get list of changed files from workflow dispatch event:
      - name: 'Get list of changed files (from user input)'
        if: github.event_name == 'workflow_dispatch'
        id: changed-files-user-input
        run: |
          echo "all_changed_files=${{ github.event.inputs.files }}" >> $GITHUB_OUTPUT
        timeout-minutes: 5

      # Run JavaScript tests:
      - name: 'Run JavaScript tests'
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            all_changed_files="${{ steps.changed-files-user-input.outputs.all_changed_files }}"
          else
            all_changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          fi
          . "$GITHUB_WORKSPACE/.github/workflows/scripts/run_affected_tests" "$all_changed_files"
        timeout-minutes: 15
